### ISSUE TITLE
hidden size of mlp layer is 4X the bottleneck size

### ISSUE THREAD

**Issue by karpathy** [teddykoker/image-gpt#1]
https://github.com/teddykoker/image-gpt/blob/92ce11653864730263a161b642dd1b5387f07381/src/gpt2.py#L13

btw the GPT-3 paper, as well as its older versions: "we always have the feedforward layer four times the size of the bottleneck layer, dff = 4 ∗ dmodel". So this Linear should probably be 4*embed_dim for the second argument.

(also not certain that the pytorch MultiHeadAttention has a linear projection at the end of it, like openai uses "c_proj" in their code.)

**Comment by teddykoker** [comment]
Andrej, thank you for this! I'll push the fix in a few minutes. 

Regarding the projection at the end of `nn.MultiHeadAttention`: I looked over the code and it does appear that their is a linear projection after the attention heads are merged: 

https://github.com/pytorch/pytorch/blob/4ae832e1060c72cb89de1d9693629783dbe0c9a6/torch/nn/functional.py#L4147
