### ISSUE TITLE
Not able to reproduce the sample from the pretrained model

### ISSUE THREAD

**Issue by themurtazanazir** [teddykoker/image-gpt#17]
command:
```python
python src/sample.py models/mnist_gen.ckpt
```
Expected:
![image](https://user-images.githubusercontent.com/34167018/155490641-5640868a-4830-4d07-9880-46bcbbdac93c.png)
Output: 
![figure](https://user-images.githubusercontent.com/34167018/155492176-f2d6d3d2-c04d-45a1-bce9-5bd197445aad.png)

Did I miss anything?

**Comment by teddykoker** [comment]
Hi @themurtazanazir, thanks for bringing this up! It looks like I forgot to add the new model weights when I [added the final layer norm to the model](https://github.com/teddykoker/image-gpt/commit/0d8a938b6e5b7a5ff6a0c5ab6348e6c7df48a48a). You can either retrain the model, or just checkout the model code prior to the addition of the final layer norm and use that checkpoint:

```bash
git checkout 41ae1e24529544e325e4b412ed19d016a3e4c169
python src/sample.py models/mnist_gen.ckpt
```

![figure](https://user-images.githubusercontent.com/11153048/155570692-6694203d-1f66-4a57-9f31-b94c3de672a4.png)

I will update the new model weights when I get a chance.

**Comment by themurtazanazir** [comment]
I was able to reproduce it. Thanks. I'd suggest updating the models. Closing the issue.

**Comment by teddykoker** [comment]
Working on updated the models as soon as I can - I'll leave this issue until then. Glad the fix worked!

**Comment by teddykoker** [comment]
Updated the models weights, retrained with layernorm - should be good now.
