### ISSUE TITLE
May I know the source of the s_gen_cifar10.ckpt file that you shared via google drive?

### ISSUE THREAD

**Issue by anirbankarak** [teddykoker/image-gpt#21]
Its wonderful that you put so much of effort to make the IGPT in torch. I want to know how to make the   s_gen_cifar10.ckpt or what is the source of these check point. I checked the openAI's IGPT actual implementation. They used this [(https://github.com/openai/image-gpt/blob/master/download.py)] to download the dataset and check point. After executing the dounload.py it downloads multiple check point. like below
input args:
 {
    "download_dir":"/content/drive/MyDrive/ImageGPT/downloads/",
    "bert":false,
    "model":"s",
    "ckpt":"1000000",
    "clusters":false,
    "dataset":"cifar10"
}
https://openaipublic.blob.core.windows.net/image-gpt/checkpoints/igpt-s/1000000/model.ckpt-1000000.data-00000-of-00032
 
Fetching model.ckpt-1000000.data-00000-of-00032: 1.00kit [00:00, 1.05Mit/s]     
https://openaipublic.blob.core.windows.net/image-gpt/checkpoints/igpt-s/1000000/model.ckpt-1000000.data-00001-of-00032
 
Fetching model.ckpt-1000000.data-00001-of-00032: 31.5Mit [00:06, 4.76Mit/s]     
https://openaipublic.blob.core.windows.net/image-gpt/checkpoints/igpt-s/1000000/model.ckpt-1000000.data-00002-of-00032
so on..

Now for your sample.py file accepts one check point file but I have many check point file. I am bit confused how to proceed now.
I want to run your pytorch implementation against the data and checkpoint I downloaded using actual download.py file used in OpenAi image-gpt code.

**Comment by teddykoker** [comment]
Hi @anirbankarak, thanks for reaching out. The `s_gen_cifar10.ckpt` was trained using: 

```bash
python src/run.py --dataset cifar10 train configs/xxs_gen.yml
```

Unfortunately the code in this repository is not directly compatible with OpenAI's model checkpoints, which were built with tensorflow. This was also mentioned in issue #9. Unfortunately I'm not sure I have the time to add this capability in at the moment; however I did find this [notebook](https://colab.research.google.com/github/apeguero1/image-gpt/blob/master/Transformers_Image_GPT.ipynb) (attached [here](https://github.com/teddykoker/image-gpt/files/10788555/Transformers_Image_GPT.ipynb.zip) in case it gets deleted, which converts the tensorflow checkpoints into a usable model in pytorch. You can also use huggingface's transformers ImageGPT model (more information [here](https://huggingface.co/openai/imagegpt-small)). Hope this answers your question, let me know if you have any others!
