### ISSUE TITLE
No such file or directory: 'data/mnist_centroids.npy'

### ISSUE THREAD

**Issue by nthglsn** [teddykoker/image-gpt#4]
Hi Teddy, thank you for this great repo!
How to test the pre-trained model? When I run the command "python src/sample.py models/mnist_gen.ckpt" it throws me the err "No such file or directory: 'data/mnist_centroids.npy'"

Any help?

**Comment by teddykoker** [comment]
Hey Nathan, Thanks for the issue, I just added the centroids to the repo so it should work now if you pull :) Let me know!
