### ISSUE TITLE
size mismatch for centroids: copying a param with shape torch.Size([512, 3]) from checkpoint, the shape in current model is torch.Size([16, 3]).

### ISSUE THREAD

**Issue by Muhammad-Zubair** [teddykoker/image-gpt#5]
**After compute centroids**
!python src/compute_centroids.py --dataset cifar10 --num_clusters=16
**I tried to train with this command**
!python src/run.py --dataset cifar-10-batches-py train configs/s_clf.yml --pretrained=models/cifar10_gen.ckpt
**Also tried to generate samples with this command**
!python src/sample.py models/cifar10_gen.ckpt

but got this error:-

Traceback (most recent call last):
  File "src/run.py", line 91, in <module>
    args.func(args)
  File "src/run.py", line 21, in train
    model = ImageGPT.load_from_checkpoint(args.pretrained)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/core/saving.py", line 154, in load_from_checkpoint
    model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/core/saving.py", line 200, in _load_model_state
    model.load_state_dict(checkpoint['state_dict'], strict=strict)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ImageGPT:
	size mismatch for centroids: copying a param with shape torch.Size([512, 3]) from checkpoint, the shape in current model is torch.Size([16, 3]).

**Comment by teddykoker** [comment]
Hi! You should not need to regenerate the centroids for sampling as I supply the ones used for training in the `data` directory. That being said, iGPT-S (which is the config I used for CIFAR10) uses 512 clusters - not 16, so if you would like to retrain the model and create new clusters you should specify`--num_clusters=256`. Hope this helps :)
