### ISSUE TITLE
Loading Pretrained Models

### ISSUE THREAD

**Issue by JohnnyC08** [teddykoker/image-gpt#9]
Hi, I'm interested in helping implement the loading of the pretrained models.

I want to know if you can point in the right direction of what you think needs to be and I can take a look.

I see that openai has code at https://github.com/openai/image-gpt that isn't being maintained and is written in TF.

What do you think. Should we try and take those models and convert them to onnx and go from there?

**Comment by ImmortalSdm** [comment]
Hi, any update? @JohnnyC08
